# Generated by Django 5.1.3 on 2025-01-18 16:45

import apps.shared.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.shared.models.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.shared.models.UpdatedAtField(auto_now=True)),
                ('created_by_username', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', apps.shared.models.DeletedAtField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('language', apps.shared.models.LanguageField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2)),
                ('created_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('entities', django.db.models.manager.Manager()),
            ],
        ),
    ]
