# Generated by Django 5.1.3 on 2025-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auditablepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditablepost',
            old_name='created_by_user_id',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='auditablepost',
            old_name='updated_by_user_id',
            new_name='updated_by_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_by_user_id',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_by_user_id',
            new_name='updated_by_user',
        ),
        migrations.AlterField(
            model_name='auditablepost',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
