# Generated by Django 5.1.3 on 2025-01-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_by_user_id_auditablepost_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='created_by_username',
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='updated_by_user',
        ),
        migrations.RemoveField(
            model_name='auditablepost',
            name='updated_by_username',
        ),
    ]
